apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  labels:
    app: {{ template "prometheus-operator-addons.name" . }}
    chart: {{ template "prometheus-operator-addons.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    thanos-component: query
    thanos-scrape: "query"
spec:
  type: NodePort
  selector:
    app: {{ template "prometheus-operator-addons.name" . }}
    release: {{ .Release.Name }}
    thanos-component: query
  ports:
  - port: 9090
    protocol: TCP
    targetPort: http
    name: http-query
