apiVersion: v1
kind: Service
metadata:
  name: thanos-query-grpc
  labels:
    app: {{ template "prometheus-operator-addons.name" . }}
    chart: {{ template "prometheus-operator-addons.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
    beta.cloud.google.com/backend-config: '{"default": "thanos-ingress"}'
    cloud.google.com/neg: '{"ingress":false}'
spec:
  type: NodePort
  selector:
    app: {{ template "prometheus-operator-addons.name" . }}
    release: {{ .Release.Name }}
    thanos-component: query
  ports:
  - port: {{ .Values.thanos.query.grpcPort }}
    protocol: TCP
    targetPort: grpc
    name: grpc
    nodePort: 30333
