{{ if .Values.thanos.query.nginxMux }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-query-nginx-config
data:
  nginx.conf: |
    events {}
    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent"';
     
        server {
            listen 11901 http2 ssl;
            ssl_certificate /etc/certs/tls.crt;
            ssl_certificate_key /etc/certs/tls.key;
{{- if .Values.thanos.mTLSEnabled }}
            ssl_verify_client optional_no_ca;
            ssl_client_certificate /etc/certs/ca/tls.crt;
{{- end }}
     
            access_log /var/log/nginx-access.log main;
     
            location = / {
                proxy_pass http://localhost:10902/graph;
            }
            location / {
{{- if .Values.thanos.mTLSEnabled }}
                if ($ssl_client_verify != SUCCESS) {
                  return 403;
                }
{{- end }}

                # Replace localhost:50051 with the address and port of your gRPC server
                # The 'grpc://' prefix is optional; unencrypted gRPC is the default
                grpc_pass grpc://localhost:10901;
            }
        }
    }
{{ end }}
