apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecars-prometheus
  labels:
    app: {{ template "prometheus-operator-addons.name" . }}
    chart: {{ template "prometheus-operator-addons.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    thanos-scrape: "sidecar"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 10902
      targetPort: http
    - name: grpc
      port: 10901
      targetPort: {{ .Values.thanos.query.sidecarService.targetPort }}
  selector:
    {{ .Values.thanos.query.sidecarService.selectorLabel.key }}: {{ .Values.thanos.query.sidecarService.selectorLabel.value | quote }}
